#!/usr/bin/env python

import os, sys

if os.environ['MYKE_REL_PATH'] == 'SUB':
    print 'true'
    sys.exit()

name, ext = os.path.splitext(os.environ['MYKE_REL_PATH'])
assert name=='a'
assert len(ext)==2  and  ext[0]=='.'
ext = ext[1:]

if ext == 'z': target = 'SUB/a.a'
else: target = 'a.%s'%(chr(ord(ext)+1),)
print 'md5sum %r >%r'%(os.path.abspath(os.environ['MYKE_REL_PATH']), target)

